version: '3'
services:
 db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  pgdata: